name: Small Stuff Digital
favicon: null
layout_spectrum: 0.7125345240347087
typography_spectrum: 0.9805241650901735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8729259567335248
  lightness: 0.1039815351832658
  saturation: 0.8803621446713805
  rhythmicContrast: 0.8443064887542278
purpose: []
